version: "3.8"
services:
  frr1:
    image: frrouting/frr-debian:latest
    container_name: frr1
    hostname: frr1
    privileged: true
    volumes:
      - "./volume/frr/daemons:/etc/frr/daemons"
      - "./volume/frr/frr1.conf:/etc/frr/frr.conf"
    networks:
      - mgmt
    tty: true
    stdin_open: true

  frr2:
    image: frrouting/frr-debian:latest
    container_name: frr2
    hostname: frr2
    privileged: true
    volumes:
      - "./volume/frr/daemons:/etc/frr/daemons"
      - "./volume/frr/frr2.conf:/etc/frr/frr.conf"
    networks:
      - mgmt
    tty: true
    stdin_open: true

networks:
  mgmt:
    driver: "bridge"
    ipam:
      driver: default
      config:
        - subnet: "192.168.100.0/24"
